[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[env]
TERM = "alacritty"

[font]
size = 12.0

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
opacity = 0.7
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"
