#! /bin/bash

UPOWER_OUTPUT=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1)
PERCENTAGE=$(echo "$UPOWER_OUTPUT" | grep percentage | awk '{print $NF}')
CHARGING=$(echo "$UPOWER_OUTPUT" | grep state | awk '{print $NF}')

# Calculate color
LOW_BATTERY_WARNING=""
if [ "$CHARGING" != "discharging" ]; then
	COLOR="yellow"
elif [ "${PERCENTAGE//%/}" -le "20" ]; then
	COLOR="pink"
	LOW_BATTERY_WARNING="!------------------------------------------------------------!"
fi

# Format and print
echo "$LOW_BATTERY_WARNING<fc=$COLOR> $PERCENTAGE</fc>"
