#! /bin/bash

data="'$(bluetoothctl devices | cut -f2 -d' ' | while read uuid; do bluetoothctl info $uuid; done | grep -e "Device\|Connected\|Name" | xargs)'"
# echo $data
echo $(
	python <<EOF
import re
y = [i.split("Connected: ") for i in re.findall(r'Name:.+?Connected: \w+', $data)]
res = ""
for i in y:
    if i[1] == 'yes':
        res += f'{i[0].replace("Name: ", "").strip()}, '

res = res[:-2] if res else "None"
print(f"<fc=#157dad><fn=1></fn> {res}</fc>")

EOF
)
