#!/bin/bash

day="$(date +%a)"
num=$(echo "-0.35*s(2.2*$(date +%u)-3.74)+.12*$(date +%u)+1.3" | bc -l | cut -f1 -d ".")
# num=$(echo "0.5*s(3.1415*$(date +%u))+.124*($(date +%u))+2.7" | bc -l | cut -f1 -d ".")
# echo "${day::num} $(date +%d.%m.%y\ %H:%M:%S)"
echo "${day::num} $(date +%d.%m.%y\ %H:%M:%S) <fc=#bfa632>[ GMT $(date -u +%d.%m.%y\ %H:%M:%S) ]</fc>"
