#!/bin/bash

total=$(free --mega | tail -2 | head -1 | awk '{print $2}')
used=$(free --mega | tail -2 | head -1 | awk '{print $3}')
p=$((used * 100 / total))

printf "%s%s (%s%s)" "$p" "%" "$used" "M"
