#! /bin/bash

if (ping -q -w 1 -c 1 8.8.8.8 >/dev/null 2>&1); then
	updates=$(checkupdates | wc -l)
	printf "%s%s%s" "$updates Update" "$([ "$updates" != "1" ] && echo "s")" "$([ "$updates" == "69" ] && echo " ( NICE )")"
else
	echo "Error: no connection"
fi
